## 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
- Contents
 - Series(변환, 인덱스 구조, 원소 선택)
 - DataFrame(변환, 인덱스, 삭제, 선택, 추가, 변경, 전치 등)

In [1]:
# 시리즈 클래스 만들기
# 딕셔너리를 시리즈로 변환
import pandas as pd

dic_data = {'a':1,'b':2,'c':3}
sr = pd.Series(dic_data)
print(sr,type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [3]:
# 리스트를 시리즈로 변환
list_data = ['1111',111,'ABC',1111,True]
sr = pd.Series(list_data, index=['a','b','c','d','e'])
print(sr,type(sr))

a    1111
b     111
c     ABC
d    1111
e    True
dtype: object <class 'pandas.core.series.Series'>


In [4]:
idx = sr.index
print(idx,'\n')
val = sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object') 

['1111' 111 'ABC' 1111 True]


In [5]:
# 튜플을 시리즈로 변환
tup_data = ('영인','5555','여',True)
sr = pd.Series(tup_data, index = ['이름','생년','성별','진실'])
print(sr,type(sr))

이름      영인
생년    5555
성별       여
진실    True
dtype: object <class 'pandas.core.series.Series'>


In [11]:
print(sr[0])

print(sr['이름'],'\n')

print(sr[1:3],'\n')

print(sr[[1,3]])


영인
영인 

생년    5555
성별       여
dtype: object 

생년    5555
진실    True
dtype: object


In [15]:
# 배열을 시리즈로 변환
import numpy as np

s1 = np.arange(start =11,stop = 16)
s2 = pd.Series(s1, index=['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [17]:
print(s2[1:3]) #뽑기
print(s2[[1,3]])

ED2    12
ED3    13
dtype: int32
ED2    12
ED4    14
dtype: int32


In [18]:
# 시리즈를 배열로 변환
print(type(s2))
ar = np.array(s2)
print(ar,type(ar))

<class 'pandas.core.series.Series'>
[11 12 13 14 15] <class 'numpy.ndarray'>


In [20]:
# Q 4가지 자료형 데이터를 생성하고 각 시리즈로 변환하여 출력

lidata = [2,3,4,5]
tudata = (True,False,True,True)
dicdata = {'김첨지':'설렁탕','점순이':'감자','나':'아달린'}
arrdata = np.array(['살바도르','빈센트','파블로','램브란트'])
index = ['1번','2번','3번','4번']

li = pd.Series(lidata,index)
tu = pd.Series(tudata,index)
dic = pd.Series(dicdata)
arr = pd.Series(arrdata,index)

print(li,'\n',tu,'\n',dic,'\n',arr)


1번    2
2번    3
3번    4
4번    5
dtype: int64 
 1번     True
2번    False
3번     True
4번     True
dtype: bool 
 김첨지    설렁탕
점순이     감자
나      아달린
dtype: object 
 1번    살바도르
2번     빈센트
3번     파블로
4번    램브란트
dtype: object


In [69]:
data = np.arange(1000,5000,1000)
obj = pd.Series(data)
state = ['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index = state
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [70]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [71]:
obj['Newyork'] = 3000

In [72]:
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Newyork      3000.0
Name: population, dtype: float64

In [73]:
obj.Newyork

3000.0

In [74]:
obj.isnull()

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Newyork      False
Name: population, dtype: bool

## 데이터프레임
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래
- 데이터프레임의 열은 각각 시리즈 개체
- 시리즈를 열벡터하고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열 벡터(mx1행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(1xm 행렬)은 m원소들의 단일 행 행렬
- 리스트, 딕셔너리, 배열 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음

In [22]:
# 배열 - > 데이터 프레임
ar = np.random.randint(100,120,size=(3,3))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index =['d1','d2','d3'],
                    columns = ['pd','sales','int'])
print(df,type(df))

[[104 107 102]
 [112 107 113]
 [107 111 105]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  104    107  102
d2  112    107  113
d3  107    111  105 <class 'pandas.core.frame.DataFrame'>


pandas indexing
- iloc :
- loc : 

In [25]:
# 행 선택
print(df.iloc[1],'\n')
print(df.loc['d2'])

pd       112
sales    107
int      113
Name: d2, dtype: int32 

pd       112
sales    107
int      113
Name: d2, dtype: int32


In [28]:
# 특정 행,열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales'])

107 

107


In [32]:
# 행,열 추가
df1 = df.copy()
df1.loc['d5'] = 0
df1

pd  sales  int
d1  104    107  102
d2  112    107  113
d3  107    111  105
d5    0      0    0

In [35]:
# 열 추가
df1['pf'] = [123,111,11111,11111]
df1

pd  sales  int     pf
d1  104  107.0  102    123
d2  112    NaN  113    111
d3  107  111.0  105  11111
d5    0    0.0    0  11111

In [39]:
print(df1.pf,type(df1.pf))

d1      123
d2      111
d3    11111
d5    11111
Name: pf, dtype: int64 <class 'pandas.core.series.Series'>


In [33]:
# 원소 값 변경
df1.iloc[1,1] = np.nan
df1

pd  sales  int
d1  104  107.0  102
d2  112    NaN  113
d3  107  111.0  105
d5    0    0.0    0

In [49]:
# 사전 -> 데이터프레임
sp1 = np.arange(1,6)
df = pd.DataFrame({
    'col1': sp1,
    'col2': sp1 * 2,
    'col3': ['A','B','C','D','E']
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

## 스칼라

In [75]:
# 딕셔너리에서 값이 스칼라이면 인덱스 필요

dic = {'A':1,'B':2,'C':3,'D':4}
# dic = {'A':[1],'B':[2],'C':[3],'D':[4]}
columns=['a','b','c','d','e']
index=[1,2,3,4]

df_dic = pd.DataFrame(dic,index)
# df_dic = pd.DataFrame(dic)
print(df_dic)

   A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4


In [50]:
# 리스트 -> 데이터 프레임
a = np.random.randint(1,5,size=(10,5))
list1 = a.tolist()
list1
index = np.arange(1,11)
df = pd.DataFrame(list1,index,columns=['c1','c2','c3','c4','c5'])
df


c1  c2  c3  c4  c5
1    2   4   1   3   1
2    2   2   2   2   4
3    3   3   4   4   3
4    2   4   3   2   1
5    1   4   3   3   4
6    1   2   4   2   1
7    4   1   1   1   2
8    3   3   2   3   3
9    3   4   2   3   3
10   2   3   1   1   3

In [54]:
# 데이터 프레임-> 배열,리스트,딕셔너리
ar = df.values
print(ar,type(ar),'\n')
li = df.values.tolist()
print(li,type(li),'\n')
dict = df.to_dict('list')
print(dict)

[[2 4 1 3 1]
 [2 2 2 2 4]
 [3 3 4 4 3]
 [2 4 3 2 1]
 [1 4 3 3 4]
 [1 2 4 2 1]
 [4 1 1 1 2]
 [3 3 2 3 3]
 [3 4 2 3 3]
 [2 3 1 1 3]] <class 'numpy.ndarray'> 

[[2, 4, 1, 3, 1], [2, 2, 2, 2, 4], [3, 3, 4, 4, 3], [2, 4, 3, 2, 1], [1, 4, 3, 3, 4], [1, 2, 4, 2, 1], [4, 1, 1, 1, 2], [3, 3, 2, 3, 3], [3, 4, 2, 3, 3], [2, 3, 1, 1, 3]] <class 'list'> 

{'c1': [2, 2, 3, 2, 1, 1, 4, 3, 3, 2], 'c2': [4, 2, 3, 4, 4, 2, 1, 3, 4, 3], 'c3': [1, 2, 4, 3, 3, 4, 1, 2, 2, 1], 'c4': [3, 2, 4, 2, 3, 2, 1, 3, 3, 1], 'c5': [1, 4, 3, 1, 4, 1, 2, 3, 3, 3]}


In [61]:
# Q 배열,리스트,딕셔너리로 데이터 프레임 생성 후 다시 변경
# 배열
ar = np.random.randint(100,120,size=(3,3))
print(ar,type(ar),'\n')
df = pd.DataFrame(ar,index =['d1','d2','d3'],
                    columns = ['pd','sales','int'])
print(df,type(df))
ar = df.values
print(ar,type(ar),'\n')

# 리스트

li = ['a','b','c','d']
print(li,type(li),'\n')
df = pd.DataFrame(li,index =[1,2,3,4])
print(df,type(df))
li = df.values.tolist()
print(li,type(li),'\n')


# 딕셔너리
sp1 = np.arange(1,6)
df = pd.DataFrame({
    'col1': sp1,
    'col2': sp1 * 2,
    'col3': ['A','B','C','D','E']
})
print(df,type(df))
dict = df.to_dict('list')
print(dict,type(dict))

[[116 105 115]
 [103 108 112]
 [109 117 118]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  116    105  115
d2  103    108  112
d3  109    117  118 <class 'pandas.core.frame.DataFrame'>
[[116 105 115]
 [103 108 112]
 [109 117 118]] <class 'numpy.ndarray'> 

['a', 'b', 'c', 'd'] <class 'list'> 

   0
1  a
2  b
3  c
4  d <class 'pandas.core.frame.DataFrame'>
[['a'], ['b'], ['c'], ['d']] <class 'list'> 

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E <class 'pandas.core.frame.DataFrame'>
{'col1': [1, 2, 3, 4, 5], 'col2': [2, 4, 6, 8, 10], 'col3': ['A', 'B', 'C', 'D', 'E']} <class 'dict'>


In [62]:
ar = np.arange(1,6)
ar2=ar*2
li = ar2.tolist()
df = pd.DataFrame({
    'col1': ar,
    'col2': li,
    'col3': np.nan})
print(df,type(df),'\n')
print(df.values,type(df.values),'\n')
print(df.values.tolist(),type(df.values.tolist()),'\n')
print(df.to_dict('l`

   col1  col2  col3
0     1     2   NaN
1     2     4   NaN
2     3     6   NaN
3     4     8   NaN
4     5    10   NaN <class 'pandas.core.frame.DataFrame'> 

[[ 1.  2. nan]
 [ 2.  4. nan]
 [ 3.  6. nan]
 [ 4.  8. nan]
 [ 5. 10. nan]] <class 'numpy.ndarray'> 

[[1.0, 2.0, nan], [2.0, 4.0, nan], [3.0, 6.0, nan], [4.0, 8.0, nan], [5.0, 10.0, nan]] <class 'list'> 

{'col1': [1, 2, 3, 4, 5], 'col2': [2, 4, 6, 8, 10], 'col3': [nan, nan, nan, nan, nan]} <class 'dict'> 



In [79]:
# file 생성, 저장, 읽기
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['차림표'])
df1.to_csv("./dataset/file_data.csv", index=None)
file_data = pd.read_csv("./dataset/file_data.csv")
file_data

차림표
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동

In [80]:
# file 생성
li = ['a','b','c','d']
df = pd.DataFrame(li,index =[1,2,3,4],columns =['d'])
# df.to_csv("./datatest/file_data.csv", index=None) #인덱스가 중복되서 넣음
#파일생성 ,괄호안에는 저장할 위치가 들어가야함
file_data = pd.read.csv("") # 괄호안은 파일이름
file_data # 파일 불러오기임

AttributeError: module 'pandas' has no attribute 'read'