### Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공

- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

### Numpy 특징

- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
!pip install numpy

In [2]:
import numpy as np
z = np.arange(10)
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [4]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 11.5 ms


In [211]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 547 ms


In [10]:
# 배열 연산
# np.random.randn 가우시안 표준 정규분포에서 난수 매트릭스 array 생성
data = np.random.randn(2,3) 
print(data, '\n')
print(data * 10, '\n')
print(data + data)

[[-0.06349282 -0.33832487  0.54876493]
 [-0.7336287  -0.10842476 -0.83316193]] 

[[-0.6349282  -3.38324873  5.48764931]
 [-7.33628705 -1.08424762 -8.33161932]] 

[[-0.12698564 -0.67664975  1.09752986]
 [-1.46725741 -0.21684952 -1.66632386]]


In [11]:
print(data.shape) #크기
print(data.dtype) #데이터 타입
print(data.ndim) #차원


(2, 3)
float64
2


#다차원 배열
<img src = 'numpy차원.jpg' STYLE = 'width:300px;'>

In [9]:
import numpy as np
data2 = [[1,2,3,4],[5,6,7,8]]
print(type(data2),'\n')
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [10]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [11]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1),array1.shape) #(.열)이 아닌 (열.)형태 출력

[1 2 3] <class 'numpy.ndarray'> (3,)


In [ ]:
# 2차원 배열로 2개의 행(row)과 3개의 열(column) 으로 구성된 6개 데이터

In [212]:
import numpy as np
data2 = [[1,2,3],[4,5,6]]
array2 = np.array(data2)
print(array2,type(array2),array2.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [18]:
array2 = np.array([[1,2,3],
                 [2,3,4]])
print(array2,type(array2),array2.shape)

[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)


In [19]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열
array21 = np.array([[1,2,3]])
print(array21,array21.shape)

[[1 2 3]] (1, 3)


In [29]:
# 3차원
array3 = np.array([[[1,2,3],[4,5,6]],
                  [[1,2,3],[4,5,6]],
                  [[1,2,3],[4,5,6]]])


print(array3, array3.shape,'\n')
print(type(array3)) 


# 2행 3열짜리 3개 3차원에 존재

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] (3, 2, 3) 

<class 'numpy.ndarray'>


In [30]:
# 경고 메시지 제외 처리
import warnings
warnings.filterwarnings('ignore')

## 배열 생성 및 초기화

- Numpy 는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [32]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [41]:
print(np.ones(10),'\n')
print(np.ones((3,6)),'\n')
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [42]:
ar1 = np.full((2,2),5)
ar1

array([[5, 5],
       [5, 5]])

In [43]:
# 항등행렬,단위행렬 이런게 있다.
ar2 = np.eye(3)
ar2 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# [과제] zeros_like, ones_like,full_like 함수 구글링해서 예제 1개씩 만들기

In [44]:
# arange 함수 : python range 함수의 배열 버전
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr2 = arr1.reshape(3,5) # 2차원
print(arr2,'\n')
arr3 = arr1.reshape(1,3,5) # 3차원
print(arr3,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] 



In [49]:
# Q. array1에 reshape 함수를 이용,(5,2) 배열을 생성하고 크기를 출력
array1 = np.arange(10)
array2 = array1.reshape(5,2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
#0~29 일차원 배열을 생성한 후 다시 2,3,차원 배열로 변환하여 출력
array1 = np.arange(30)
array2 = array1.reshape(6,5)
print(array2,array2.shape,'\n')
array3 = array1.reshape(1,6,5)
print(array3,array3.shape)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] (6, 5) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] (1, 6, 5)


In [55]:
# reshape(-1,-1) 이용 , 차원 변경
array1 = np.arange(30)
ar12 = array1.reshape(5,-1)
print(ar12,ar12.shape,'\n')
ar13 = array1.reshape(-1,2,5)
print(ar13,ar13.shape,'\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [7]:
# 2 -> 1,3차원으로 변환하여 출력
array1 = np.arange(30)
ar12 = array1.reshape(-1)
ar13 = array1.reshape(3,2,-1) # -1이 붙으면 자동완성 인것같네
print(ar12,ar12.shape,'\n')
print(ar13,ar13.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [58]:
# 3 -> 1,2차원 변경
ar3 = np.arange(30)
ar1 = ar3.reshape(-1)
ar2 = ar3.reshape(2,-1)
print(ar1,ar1.shape,'\n')
print(ar2,ar2.shape,'\n')


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] (2, 15) 



## 행렬의 종류

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [59]:
# 정방행렬
a = np.full((5,5),7)
a

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [60]:
# 항등행렬, 단위행렬
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
# 영행렬
a = np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ndarray 데이터 형태 지정 및 변경

<img src = '데이터형태.jpg' STYLE = 'width:300px;'>

In [65]:
# 데이터 타입 확인
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2, arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [66]:
# 타입 변경
arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [72]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf.zeros함수
# 실행할 때마다 값이 다른 것을 확인 할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 
# 남아있떤지 상관없이 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문
print(np.empty(shape=(10,),dtype = np.int8))
print(np.zeros(shape=(10,),dtype = np.int8))

[  64  -17   59 -128  -74    1    0    0    0    0]
[0 0 0 0 0 0 0 0 0 0]


In [75]:
# 문자열 타입으로 배열 만들기
# arr = np.array([1,2,3,4], dtype ='S')
arr = np.array([1,2,3,4], dtype =np.string_)
print(arr,arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [74]:
arr1 = arr.astype(float) # 뒤에 숫자가 없어도 default 값이 자동으로 들어간다.
print(arr,arr1.dtype) # ('float32') -> default 값이 아닌 다른 값을 쓸때 써야됨.

[b'1' b'2' b'3' b'4'] float64


In [78]:
# 정수와 실수로 구성된 list_e = [1,2,2,3,3]을 numpy를 이용해 실수,정수로 뽑아라
list_e = [1,2,2,3,3]
arr1 = np.array(list_e,dtype=np.float64)
arr2 = np.array(list_e,dtype=np.int32)
print(arr1,arr1.dtype,'\n')
print(arr2, arr2.dtype)

[1. 2. 2. 3. 3.] float64 

[1 2 2 3 3] int32


In [81]:
list_e = [1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype,'\n')
array_e2 = array_e1.astype(int)
print(array_e2,array_e2.dtype,'\n')

[1.2 2.3 3. ] float64 

[1 2 3] int32 



In [82]:
# 배열의 산술 연산
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)


[[1 2 3]
 [4 5 6]] int32


In [90]:
arr * arr

array([[  0.,  16.,   1.],
       [ 49.,   4., 144.]])

In [89]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [87]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [91]:
arr2 > arr

array([[False, False, False],
       [False, False, False]])

In [99]:
# 기본 사칙 연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)

a = value2 * value1
b = value2 + value1
c = value2 - value1
d = value2 / value1
print(a,b,c,d)
print(np.add(value1,value2),'\n') # 더하기
print(np.subtract(value2,value1),'\n') # 빼기
print(np.multiply(value2,value1),'\n') # 곱하기 
print(np.divide(value2,value1),'\n') # 나누기


[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] [[12 14 16]
 [18 20 22]
 [24 26 28]] [[10 10 10]
 [10 10 10]
 [10 10 10]] [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 



In [100]:
arr = np.random.randn(5,4)
arr

array([[ 0.98532475, -0.42742051, -1.65843785,  0.92206831],
       [ 0.81453708,  0.65303983,  1.35241757, -0.53106119],
       [-0.79079582,  1.53516279, -0.43041108, -1.24602189],
       [-0.3813673 ,  1.04329439, -0.13479538, -1.48886711],
       [-0.37463016,  0.14101327,  0.25223678,  1.80323945]])

In [103]:
arr.mean(),round(4)

(0.10192629653565169, 4)

In [107]:
arr.mean(axis=1)

array([-0.04461633,  0.57223332, -0.2330165 , -0.24043385,  0.45546484])

In [110]:
arr.mean(axis = 0)b

array([ 0.05061371,  0.58901795, -0.12379799, -0.10812849])

In [111]:
arr.sum().round(4)

2.0385

In [116]:
arr.cumprod()

array([ 9.85324747e-01, -4.21148006e-01,  6.98447793e-01,  6.44016574e-01,
        5.24575379e-01,  3.42568615e-01,  4.63295814e-01, -2.46038425e-01,
        1.94566157e-01,  2.98690724e-01, -1.28559798e-01,  1.60188322e-01,
       -6.10905872e-02, -6.37354670e-02,  8.59124636e-03, -1.27912242e-02,
        4.79197839e-03,  6.75732563e-04,  1.70444607e-04,  3.07352439e-04])

In [10]:
# 인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
arr2d[2:]

array([[7, 8, 9]])

In [215]:
arr2d[2][2]

9

In [216]:
arr2d[:,0]

array([1, 4, 7])

In [217]:
arr2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# arr2d를 다은 방식으로 아래와 같이 출력하세요.
[[1, 2, 3],
[4, 5, 6]]

In [219]:
# arr2d[:2][:]
arr2d[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
# arr2d에서 [3,6], [[1,2],[4,5]]을 출력하세요.
print(arr2d[:2,2])
print()
print(arr2d[:2,:2])

[3 6]

[[1 2]
 [4 5]]


In [130]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [152]:
print(arr[2][2:5]) # [] 앞이 행 [] 열과 열안에 순서, 행이 세로 열이 가로
print(arr[[0,1],3])
print(arr[[0,1,2],1])
print(arr[:3,1]) # 3번째 행 앞까지, 열안에 순서 

[14 15 16]
[3 9]
[ 1  7 13]
[ 1  7 13]


In [157]:
# 배열을 리스트로 변환
li = arr.tolist()
print(li, type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [163]:
# boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d>5] # 잘보자
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [171]:
# arr1d에서 일반 인덱스를 이용해서 [6,7,8,9]를 출력
print(arr1d[5:])
print(arr1d[5:9])

[6 7 8 9]
[6 7 8 9]


In [179]:
# Q 1~14까지 ndarray를 만들어 array_e로 지정하고 array_e/2 > 5을 인덱스로 추출

ndarray = np.arange(1,15)
print(ndarray)
array_e = ndarray[(ndarray / 2) > 5]
print(array_e)
print(ndarray[10:])
print((ndarray/2) > 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[11 12 13 14]
[11 12 13 14]
[False False False False False False False False False False  True  True
  True  True]


In [21]:
ndarray = np.arange(15)
array_e = ndarray[ndarray/2 >5]
print(array_e)

[11 12 13 14]


In [180]:
# Q
names = np.array(['Bob','Joe','Will','Bob','Joe','Will','Joe'])
data = np.random.randn(7,4)
print(names,'\n')
print(data)


['Bob' 'Joe' 'Will' 'Bob' 'Joe' 'Will' 'Joe'] 

[[ 0.91059118  0.40004098  0.63028804  0.24027392]
 [ 0.28086694  0.13929879 -0.30825581 -1.17491726]
 [ 1.08487772  0.00226345 -0.07415652  1.30962553]
 [ 0.75465218 -0.07031259 -0.57476968 -1.37852708]
 [ 1.53428106 -0.79094339 -0.4352792  -0.60457467]
 [-1.85955409 -0.94025101 -1.90514724  0.46007073]
 [-0.54642139  0.47378965 -1.81765321  1.22247644]]


In [181]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [182]:
data[names == 'Bob']

array([[ 0.91059118,  0.40004098,  0.63028804,  0.24027392],
       [ 0.75465218, -0.07031259, -0.57476968, -1.37852708]])

In [183]:
data[names == 'Bob', 2:]

array([[ 0.63028804,  0.24027392],
       [-0.57476968, -1.37852708]])

In [186]:
data[names != 'Bob']

array([[ 0.28086694,  0.13929879, -0.30825581, -1.17491726],
       [ 1.08487772,  0.00226345, -0.07415652,  1.30962553],
       [ 1.53428106, -0.79094339, -0.4352792 , -0.60457467],
       [-1.85955409, -0.94025101, -1.90514724,  0.46007073],
       [-0.54642139,  0.47378965, -1.81765321,  1.22247644]])

In [199]:
# Bob이거나 Will인것 출력
data[names != 'Joe']

array([[ 0.91059118,  0.40004098,  0.63028804,  0.24027392],
       [ 1.08487772,  0.00226345, -0.07415652,  1.30962553],
       [ 0.75465218, -0.07031259, -0.57476968, -1.37852708],
       [-1.85955409, -0.94025101, -1.90514724,  0.46007073]])

In [202]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 0.91059118,  0.40004098,  0.63028804,  0.24027392],
       [ 1.08487772,  0.00226345, -0.07415652,  1.30962553],
       [ 0.75465218, -0.07031259, -0.57476968, -1.37852708],
       [-1.85955409, -0.94025101, -1.90514724,  0.46007073]])

In [208]:
# 음수를 모두 0으로 처리하여 출력
data[data<0] = 0  # 잘보자
print(data)



[[0.91059118 0.40004098 0.63028804 0.24027392]
 [0.28086694 0.13929879 0.         0.        ]
 [1.08487772 0.00226345 0.         1.30962553]
 [0.75465218 0.         0.         0.        ]
 [1.53428106 0.         0.         0.        ]
 [0.         0.         0.         0.46007073]
 [0.         0.47378965 0.         1.22247644]]


In [3]:
# Fancy indexing
arr = np.empty((8,4))
arr 
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [5]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [7]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

arr[[1,5,7,2],[0,3,1,2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [10]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]]) ## 열 순서 바꾸기 
# 순서는 여기도 똑같이 0부터 시작임

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [11]:
# 배열 전치와 축 바꾸기
arr = np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
