In [3]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,size=[5,5]) # randint 랜덤하게 정수를 뽑음
# 1~10사이 숫자를 가지고 5행 5열짜리 정수 매트릭스를 만든다. 중복 상관x
arr

array([[9, 8, 4, 6, 4],
       [1, 1, 4, 4, 2],
       [9, 5, 9, 1, 2],
       [4, 3, 7, 4, 4],
       [4, 2, 4, 8, 6]])

In [4]:
arr.T # 행과 열이 바뀌는 거임 T는 

array([[9, 1, 9, 4, 4],
       [8, 1, 5, 3, 2],
       [4, 4, 9, 7, 4],
       [6, 4, 1, 4, 8],
       [4, 2, 2, 4, 6]])

In [5]:
np.transpose(arr) # 그냥 T 쓰자 

array([[9, 1, 9, 4, 4],
       [8, 1, 5, 3, 2],
       [4, 4, 9, 7, 4],
       [6, 4, 1, 4, 8],
       [4, 2, 2, 4, 6]])

In [6]:
# 행렬곱, 내적
np.dot(arr.T , arr) # 중요 

array([[195, 138, 165, 115,  96],
       [138, 103, 110,  85,  68],
       [165, 110, 178, 109,  94],
       [115,  85, 109, 133,  98],
       [ 96,  68,  94,  98,  76]])

In [10]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y = np.swapaxes(a,0,1) # 축을 스왑 2행3열을 3행2열로 변환
# 0은 2차원(열) 1은 1차원(행)
print(y,'\n')
y = a.T
print(y)


[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [45]:
# 1~100 을 출력
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [46]:
a = np.arange(1, 101).reshape((10, -1))

for i in range(10):
    if i % 2 == 1:
        a[i] = a[i][::-1]

print(a)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [51]:
# (0,1,2)
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))  # 3차와 2차를 바꾸니까 2차를 먼저주고 3차를 그담에 준다
print(y,y.shape,'\n') # transpose 조건 받으려면 어쩔수 없이 써야겠네

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [58]:
# (1,2,3) -> (2,3,1)
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,2,0))
print(y,y.shape,'\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1) 



In [61]:
# 나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.remainder(value1,value2))

[1 2 0]
[1 2 0]


In [64]:
# 각 수의 역수를 구해주는 함수
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value))

value1 = np.array([100],dtype = int)
print(value1,'\n')
print(np.reciprocal(value1,dtype=float))

[1.17647059 0.54054054 1.         0.01      ]
[100] 

[0.01]


In [65]:
# 승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,16])
value2 = np.array([1,2,3])

print(np.power(value1,2),'\n')
print(np.power(value1,value2))

[  4 100 256] 

[   2  100 4096]


In [68]:
arr = np.random.randn(10)
# print(arr.mean(),'\n')
# print(arr.std())
arr

array([-1.61662093, -0.6504532 ,  0.52868308,  0.17475684, -2.09212424,
        0.78951995,  0.75819741,  1.32040462, -0.70817185, -0.13417091])

In [69]:
# 양수인 원소의 개수
(arr > 0 ).sum()

5

In [72]:
# 하나 이상의 값이 true인지 검사
bools = np.array([False,False,True,True])
bools.any()

True

In [73]:
# 모든 원소가 true인지 검사
bools.all()

False

In [79]:
# 상황식의 벡터화 버전 ( 앞에 조건을 만족하면 앞에있는거 불만족하면 뒤에있는거)
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr>0, 2 ,-2)

[[ 0.11381861 -0.28195887 -1.86147002 -0.24457435]
 [ 0.68122301 -0.04133535  0.22701666  0.03646412]
 [ 0.5080571  -0.49986854 -2.89345441 -0.99088393]
 [ 1.38339283  1.50580224 -0.06828298 -1.4627862 ]] 



array([[ 2, -2, -2, -2],
       [ 2, -2,  2,  2],
       [ 2, -2, -2, -2],
       [ 2,  2, -2, -2]])

In [78]:
arr = np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2 ,arr)

[[ 1.21580617  0.63090502 -0.69844327 -0.51853411]
 [-1.12945715  0.29581033 -0.70355971 -0.09944767]
 [-0.04347352  1.19768008  0.60810815  0.67733084]
 [ 1.60439148  1.01520655  0.41331583  1.78920021]] 



array([[ 2.        ,  2.        , -0.69844327, -0.51853411],
       [-1.12945715,  2.        , -0.70355971, -0.09944767],
       [-0.04347352,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        ,  2.        ]])

In [131]:
# 2개의 1차원 배열을 받아서 가능한 모든 (x,y) 짝을 만들 수 있는 2차원 배열을 2개 반환
x = np.arange(1,1001)
y = np.arange(1,4)

xs,ys = np.meshgrid(x,y)
print(xs,'\n',ys)

[[   1    2    3 ...  998  999 1000]
 [   1    2    3 ...  998  999 1000]
 [   1    2    3 ...  998  999 1000]] 
 [[1 1 1 ... 1 1 1]
 [2 2 2 ... 2 2 2]
 [3 3 3 ... 3 3 3]]


In [83]:
# np.sort() 원본은 안바뀜
arr= np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

[72 12 69 39 16 22 27 78 23 58] 

[12 16 22 23 27 39 58 69 72 78] 

[72 12 69 39 16 22 27 78 23 58]


In [84]:
# sorted 라는걸 따로 만들어야됨.
sorted = np.sort(arr)
print(sorted)

[12 16 22 23 27 39 58 69 72 78]


In [87]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행,열 방향으로 정렬 수행
arr2d = np.array([[8,12],[7,11]])
print(arr2d,'\n')
sort_ar2d_axis0 = np.sort(arr2d,axis=0)
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis1 = np.sort(arr2d,axis=1)
print(sort_ar2d_axis1,'\n')

[[ 8 12]
 [ 7 11]] 

[[ 7 11]
 [ 8 12]] 

[[ 8 12]
 [ 7 11]] 



In [92]:
# ndarray.sort() 원본에 반영
np.random.seed(0)
arr = np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort()
arr

[2 6 5 5 1 8 4 6 4 4] 



array([1, 2, 4, 4, 4, 5, 5, 6, 6, 8])

In [94]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n') 
arr.sort(1) # 열방향
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [95]:
np.random.seed(0)
arr = np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(0) # 행방향
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [96]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할대
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) # argsort라는 함수 , 인덱스를 정렬해주네
print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [148]:
# 배열에서 정렬한 후 5% 시점에(분위수) 해당되는 요소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

-1.6796199878901026

In [11]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Bob','Joe','Will','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [13]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [14]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 boolean 배열 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [15]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리형식 .npy 파일로 저장

arr = np.arange(10)
np.save('some_array',arr)

In [16]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a = arr, b = arr)

In [21]:
arch = np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# Q 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]을 출력
a = np.ones(10,dtype=int)
a[[1,3,5,7,9]] = 0
a # 잘보자 ##########################

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [55]:
# Q a = np.arange(10) 에서 6789 출력
a = np.arange(10)
a[6:]

array([6, 7, 8, 9])

In [32]:
# Q a에서 최댓값 최솟값 출력
print(f'{a.max()}는 최댓값 {a.min()}은 최솟값')

9는 최댓값 0은 최솟값


In [58]:
# Q a에서 최댓값 최솟값의 인덱스 출력
a = np.arange(1,10)
print(f'{np.argmax(a)}는 최댓값 {np.argmin(a)}은 최솟값')

8는 최댓값 0은 최솟값


In [62]:
# a에서 인덱스 배열을 역순으로 출력
np.argsort(a)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [63]:
# np.ones((10,10))을 아래와 같이 출력
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

b=np.ones((10,10))
b[1:9,1:9]=0
b


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

[파이썬 random 함수]

In [137]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.04206213787246327 

10 

13.564800119851304 

0 

1 

[1, 2, 5] 

[4, 5, 1, 3, 2]


[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [138]:
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

3 

4 

[7 9 3 5 2 4 7 6 8 8] 

[11 16 17 17 18 11 15 19 18 19] 

[[14 13 10 13 15]
 [10 12 13 18 11]
 [13 13 13 17 10]]


In [140]:
r = np.random.rand(6) # 0 ~ 1 사이의 균일분포
print(r,'\n')
r.mean()

[0.58201979 0.53737323 0.75861562 0.10590761 0.47360042 0.18633234] 



0.4406415026179474

In [73]:
# 표준 정규분포
r = np.random.randn(6)
r.mean()

0.43261930109895247

In [75]:
list = np.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

[1 2 3 4 5] 



array([3, 2, 1, 5, 4])

In [76]:
np.random.choice(list)

4

In [78]:
a = np.array([11,11,3,3,2,2,2,7])
index,count = np.unique(a,return_counts = True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [79]:
np.random.uniform(1.0,2.0,10) # 최솟값,최댓값,몇개를 뽑아달라 # 그냥 뽑는 함수

array([1.33279604, 1.95811898, 1.65606971, 1.64637864, 1.55361818,
       1.60169528, 1.49291038, 1.5028933 , 1.1473399 , 1.2118685 ])

In [81]:
np.random.uniform(0,1,(2,3))

array([[0.11384976, 0.13785912, 0.39645625],
       [0.19284084, 0.22126597, 0.27323434]])

In [80]:
# 0~1 사이의 실수값으로 행렬 생성
np.random.random_sample((2,3))

array([[0.63166398, 0.60546745, 0.07552963],
       [0.50366214, 0.0867389 , 0.29209337]])

In [83]:
ar = np.random.rand(4,8)
ar

array([[0.43038454, 0.51687793, 0.17374589, 0.6495824 , 0.38384488,
        0.74196805, 0.46796348, 0.24929139],
       [0.0565023 , 0.15644862, 0.59096644, 0.82283312, 0.83338317,
        0.46809982, 0.10966385, 0.20424999],
       [0.40219936, 0.4106886 , 0.653626  , 0.21401233, 0.90845816,
        0.19760768, 0.44456905, 0.88744651],
       [0.06319637, 0.7999064 , 0.2307918 , 0.11739801, 0.97323319,
        0.04557363, 0.6093986 , 0.5734727 ]])

In [107]:
# 배열을 데이터 프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
df

0         1         2         3         4         5         6  \
0  0.430385  0.516878  0.173746  0.649582  0.383845  0.741968  0.467963   
1  0.056502  0.156449  0.590966  0.822833  0.833383  0.468100  0.109664   
2  0.402199  0.410689  0.653626  0.214012  0.908458  0.197608  0.444569   
3  0.063196  0.799906  0.230792  0.117398  0.973233  0.045574  0.609399   

          7  
0  0.249291  
1  0.204250  
2  0.887447  
3  0.573473

In [113]:
# Series의 합으로 구성된 데이터 타입, 시리즈가 위에 0~7을 뜻함
print(df[0])
type(df[0]) # 칼럼이 없다, 보기가 어렵다? 아마도?

0    0.430385
1    0.056502
2    0.402199
3    0.063196
Name: 0, dtype: float64


pandas.core.series.Series

In [97]:
columns  = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.430385  0.516878  0.173746  0.649582  0.383845  0.741968  0.467963   
1  0.056502  0.156449  0.590966  0.822833  0.833383  0.468100  0.109664   
2  0.402199  0.410689  0.653626  0.214012  0.908458  0.197608  0.444569   
3  0.063196  0.799906  0.230792  0.117398  0.973233  0.045574  0.609399   

       time  
0  0.249291  
1  0.204250  
2  0.887447  
3  0.573473

In [129]:
# Q id,gender,age 칼럼에 대하여 의미 있는 값으로 변환하여 3개로 구성된 df출력
ID = np.random.randint(1000,10000,3)
gen = np.random.choice(['M','F'],3)
age = np.random.randint(10,40,3)


data = np.array([ID,gen,age]).reshape(3,3).transpose()
df=pd.DataFrame(data, np.arange(1,4),['ID','Gender','Age'])
df

################### 개잘하네;

ID Gender Age
1  2247      M  20
2  5881      M  31
3  4568      M  28

In [136]:
ar = np.zeros((4,3)) # 4행3열짜리 틀
columns  = ['id','gender','age'] # 행 이름
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns = columns)
# df.id = np.array([1,2,3,4]) # 데이터 프레임. 콜럼이름
df.id = np.arange(1,5)
# df.gender = np.array([0,1,0,1])
np.random.seed(0)
df.gender = np.random.randint(2,size = 4)
df.age = np.array([20,30,40,50])
df

id  gender  age
0   1       0   20
1   2       1   30
2   3       1   40
3   4       0   50