In [5]:
import numpy as np
a = np.array([1,2,3],dtype = np.float64)
b = np.array([1,2,3],dtype = np.int32)

In [8]:
arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]


In [12]:
a  = np.arange(6).reshape(1,2,3)

y = np.transpose(a,(1,0,2))
print(a,'\n',y)

[[[0 1 2]
  [3 4 5]]] 
 [[[0 1 2]]

 [[3 4 5]]]


In [14]:
arr =np.random.randint(1,100, size = 100)
print(np.sort(arr))

[ 1  1  9  9  9  9  9 10 11 13 13 14 16 16 18 20 21 21 22 23 23 25 27 28
 29 29 29 29 30 30 30 30 31 31 31 33 33 34 36 36 36 38 38 40 40 41 42 42
 44 44 46 48 49 51 51 52 53 56 57 58 60 60 60 63 63 64 64 66 70 70 70 71
 72 74 74 75 75 75 78 79 79 79 80 82 83 83 84 86 87 87 88 88 90 91 92 96
 97 98 98 99]


In [17]:
b=np.ones((10,10))
b[1:9,1:9]=0
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
import pandas as pd
df = pd.DataFrame(ar)
df

0         1         2         3         4         5         6  \
0  0.775909  0.115671  0.404614  0.763269  0.353598  0.953887  0.900004   
1  0.916288  0.025565  0.630486  0.755646  0.528556  0.110237  0.667030   
2  0.984347  0.690416  0.067592  0.804496  0.233255  0.055359  0.431433   
3  0.618514  0.848897  0.065150  0.886028  0.246142  0.284691  0.246619   

          7  
0  0.626719  
1  0.645085  
2  0.620210  
3  0.166150

In [19]:
ar = np.random.rand(4,8)
ar

array([[0.77590904, 0.11567099, 0.40461376, 0.76326945, 0.35359835,
        0.95388652, 0.90000435, 0.62671895],
       [0.91628846, 0.02556544, 0.63048567, 0.75564636, 0.52855556,
        0.11023724, 0.66703035, 0.64508464],
       [0.98434747, 0.6904156 , 0.06759164, 0.80449628, 0.23325512,
        0.05535937, 0.43143289, 0.62021013],
       [0.61851389, 0.84889698, 0.06515033, 0.88602838, 0.24614218,
        0.28469054, 0.24661942, 0.16615002]])

In [21]:
columns  = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.775909  0.115671  0.404614  0.763269  0.353598  0.953887  0.900004   
1  0.916288  0.025565  0.630486  0.755646  0.528556  0.110237  0.667030   
2  0.984347  0.690416  0.067592  0.804496  0.233255  0.055359  0.431433   
3  0.618514  0.848897  0.065150  0.886028  0.246142  0.284691  0.246619   

       time  
0  0.626719  
1  0.645085  
2  0.620210  
3  0.166150

In [ ]:
ID = np.random.randint(10000,3)
gen = np.random.choice(['female','male'],3) 
age = np.random.randint(1,100,3)

data = np.array([ID,gen,age]).reshape(3,3).transpose()



In [23]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
a = np.arange(100)
b = a[a%3==0]
b

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)
a = np.arange(100)
b = a[a%10==0]
b

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
a = np.random.randn(1,5,5)
print(np.std(a))
print(np.mean(a))

1.0706780164679826
0.10862181509963088


In [31]:
a = np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [32]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b = np.array(a)
np.sort(b)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
a = [1,2,0,0,4,0]
b = np.array(a)
b[np.nonzero(b)]

array([1, 2, 4])

In [42]:
a = np.ones((5,5))
b = np.zeros((9,9))
b[2:7,2:7]=a
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# [과제] np.zeros(8,8) 을 이용하여 아래와 같이 출력 (tile,인덱싱)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])

In [44]:
a = np.zeros((8,8))
a[::2,1::2] = 1
a[1::2,::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])