In [6]:
import numpy as np

In [ ]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [130]:
# ones_like
test_matrix = np.arange(30).reshape(5,-1)
print(test_matrix)
np.ones_like(test_matrix, np.float32) 
#원본과 동일한 크기로 만들어짐 
# dtype을 지정해주면 원하는 data type의 배열로 생성해서 반환한다.

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [131]:
print(test_matrix)
np.zeros_like(test_matrix, np.int8)
# 1로 초기화가 아닌 0으로 초기화

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [135]:
print(test_matrix)
np.full_like(test_matrix,4) #(shape, 배열을 채울 값)
# full 함수는 shape 와 채울값 2가지

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [ ]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)

In [39]:
array = np.arange(1,101)
# case1 배열
arr = array[array%3==0]
arr1 = arr.reshape(1,11,3)
print(arr1,arr1.shape)
# case2 for문
for arr in array:
    if arr % 3 ==0:
        print(arr)

[[[ 3  6  9]
  [12 15 18]
  [21 24 27]
  [30 33 36]
  [39 42 45]
  [48 51 54]
  [57 60 63]
  [66 69 72]
  [75 78 81]
  [84 87 90]
  [93 96 99]]] (1, 11, 3)
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


In [56]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)
arr = np.arange(1,101)
# case 1
arr1 = arr[arr%10==0]
arr2 = arr1.reshape(1,2,-1)
print(arr2, arr2.shape)
# case 2
for arr1 in arr:
    if arr1 % 10 == 0:
        print(arr1)

[[[ 10  20  30  40  50]
  [ 60  70  80  90 100]]] (1, 2, 5)
10
20
30
40
50
60
70
80
90
100


In [120]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
data = np.random.randn(1,5,5) # 표준정규분포
print(data)
print(np.mean(data)) # 평균
print(np.std(data)) # 표준편차

[[[-1.20253701 -1.04212473  0.00698284 -0.4319685   0.68817584]
  [ 1.3776565  -1.72946368  0.53075942 -0.79191298  0.18198014]
  [-0.07753918 -0.08706936 -0.26093505  0.23595174  0.41298697]
  [ 0.89286167  0.30297476  0.54200399  0.12748154 -0.05455348]
  [ 1.89224576  1.16767749 -0.19926503  0.42298183 -0.57690222]]]
0.09313797026229845
0.7952815584323797


In [3]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
import numpy
print(numpy.__version__)
print(numpy.version.version)

1.21.2
1.21.2


In [8]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
help(np.add) # np,info(np.add) , np.info(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [121]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
a = np.eye(10)
a[4][:]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
a = np.arange(10,dtype = float)
b = np.zeros_like(a)
b[4]=1
b


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros(10)
arr[4]=1
arr
### 잘보자

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [105]:
import numpy as np
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.array(data)
np.sort(a)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [94]:
import numpy as np
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
data = [1,2,0,0,4,0]
a = np.array(data)
a[np.nonzero(a)]

array([1, 2, 4])

In [142]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
a1 = np.array(a)
np.sort(a)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [143]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.
a = [1,2,0,0,4,0]
a1 = np.array(a)
a1[np.nonzero(a1)]

array([1, 2, 4])

In [13]:
x = [1,2,0,0,4,0]
y = np.nonzero(x)
y # 인덱스는 나와있는 숫자가 아닌 뒤에 위치임 

(array([0, 1, 4], dtype=int64),)