In [1]:
import numpy as np

In [34]:
# (1,2,3) -> (2,3,1)
a = np.arange(16).reshape(2,2,4)
print(a,a.shape,'\n')

y = np.transpose(a,(1,2,0))
print(y,y.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]]

 [[ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]] (2, 4, 2) 



In [2]:
# [과제] 아래 배열에서 3차원과 2차원을 번갈아가면서 출력 (shape 확인)
arr = np.arange(16).reshape(2,2,4) # 출력 때는 맨앞이 3,2,1차원
print(arr,arr.shape,'\n')
# 2 2 4 => axis(0,1,2) 와 같은 뜻임 

y = np.transpose(arr,(2,0,1)) # 0,1,2 만 사용가능?  변겯 때는 2.3.1차원
print(y,y.shape,'\n')

y = np.transpose(arr,(1,0,2)) 
print(y,y.shape,'\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]] (4, 2, 2) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4) 



In [108]:
# [과제] 상기 과제의 arr에서 2차원과 1차원 번갈아가면서 출력
arr = np.arange(16).reshape(2,2,4) # 출력 때는 맨앞이 3,2,1차원
print(arr,arr.shape,'\n')

y = np.transpose(arr,(0,2,1)) 
print(y,y.shape,'\n')

arrs = arr.swapaxes(1,2)
print(arrs)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2) 



In [62]:
# [과제] np.ones((5,5))을 아래와 같이 출력
# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])
a=np.ones((5,5))
b=np.zeros((9,9))
b[2:7,2:7] = a
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
arr1 = np.ones((5,5))
np.pad(arr1,(2,2),'constant',constant_values=0) ## 구글링한 것, 패드라는 함수

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
인덱스 함수가 있었는데 실수로 지웠어 ㅣ.

In [5]:
# [과제] np.zeros(8,8) 을 이용하여 아래와 같이 출력 (tile,인덱싱)
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])
a = np.array([[0,1],[1,0]]) # 타일 함수 사용
b = np.tile(a,(4,4))
print(b)
x = np.zeros((8,8))
x[::2,1::2] = 1 ## 전체부터 2칸, 1 부터 2칸씩
x[1::2,::2] = 1 ## 첫번째부터 2칸씩, 전체부터 2칸씩
x

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [19]:
# [도전] np.arange(336).reshape(6,7,8)에서 100번재 요소의 인덱스 구하기
a = np.arange(336).reshape(6,7,8)
print(np.where(a==99),'\n')
# z = np.unravel_index(99,(np.arange(336).reshape(6,7,8)))
# print(z)

z = np.unravel_index(99,(6,7,8)) ## 이것도 맞다. 희한하네 
print(z)

(array([1], dtype=int64), array([5], dtype=int64), array([3], dtype=int64)) 

(1, 5, 3)


In [27]:
# [도전] np.arange(4)을 이용해서 아래와 같이 출력
# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])
arr=np.arange(4)
np.diag(arr+1,k=1) # diag란 함수가 있네 , 콤마 뒤가 위치 이동하는 것
# np.diag(arr+1,k=-1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [22]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

id : 1 ~ 1000번 일련번호
gender : 0,1 정수 난수 생성
age : 0 ~ 80사이 정수 난수 생성
region : 1 ~ 10 사이 정수 난수 생성 # 정수난수는 무조건 randint
product_19 : 제품코드 11111 ~ 99999
product_20 : 제품코드 11111 ~ 99999
price_19 : 1000 ~ 50000 사이 실수 난수 생성
price_20 : 1000 ~ 50000 사이 실수 난수 생성
quantity_19 : 1 ~ 100 사이 정수 난수 생성
quantity_20 : 1 ~ 100 사이 정수 난수 생성
time_19 : 01 ~ 24 사이 정수 난수 생성
time_20 : 01 ~ 24 사이 정수 난수 생성
amount_19 : price_19 * quantity_19
amount_20 : price_20 * quantity_20
sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [6]:
import random
import numpy as np
import pandas as pd

ar = np.zeros((1000,15))
columns = ['id1','gender','age','region','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(ar,index,columns = columns)


# df.id1 = np.arange(1,1001)
# np.random.seed(0)
# df.gender = np.random.randint(2,size=1000) # choice 함수 쓰는것도 좋다
# df.age = np.random.randint(1,80,size=1000)
# df.region = np.random.randint(1,10,size=1000) # 정수 난수 생성

# # 같은 번호가 나오면 같은 가격이 나오게 하기
# df.product_19 = np.random.randint(11111,99999,size=1000)
# df.product_20 = np.random.randint(11111,99999,size=1000)

# # df.price_19 = np.random.randint(1000,50000,size=1000) # 실수 난수 생성
# df.price_19 = np.random.uniform(1000,50000,1000).round(2) # 실수 난수 생성
# # df.price_20 = np.random.randint(1000,50000,size=1000)
# df.price_20 = np.random.uniform(1000,50000,1000).round(2)



# df.quantity_19 = np.random.randint(1,100,size=1000)
# df.quantity_20 = np.random.randint(1,100,size=1000)
# df.time_19 = np.random.randint(1,25,size=1000)
# df.time_20 = np.random.randint(1,25,size=1000)
# df.amount_19 = df.price_19 * df.quantity_19
# df.amount_20 = df.price_20 * df.quantity_20
# df.sales = np.where(df.amount_19 < df.amount_20, 1,0) 

print(df.shape)
df.head()
# df
# arr1 = arr[arr%10==0]

(1000, 15)


id1  gender  age  region  product_19  product_20  price_19  price_20  \
0  0.0     0.0  0.0     0.0         0.0         0.0       0.0       0.0   
1  0.0     0.0  0.0     0.0         0.0         0.0       0.0       0.0   
2  0.0     0.0  0.0     0.0         0.0         0.0       0.0       0.0   
3  0.0     0.0  0.0     0.0         0.0         0.0       0.0       0.0   
4  0.0     0.0  0.0     0.0         0.0         0.0       0.0       0.0   

   quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
0          0.0          0.0      0.0      0.0        0.0        0.0    0.0  
1          0.0          0.0      0.0      0.0        0.0        0.0    0.0  
2          0.0          0.0      0.0      0.0        0.0        0.0    0.0  
3          0.0          0.0      0.0      0.0        0.0        0.0    0.0  
4          0.0          0.0      0.0      0.0        0.0        0.0    0.0

In [35]:
df[df.sales==0]
print(len(df[df.sales==0])) # sales가 0인 애들만 골라서 길이를 구해줌
# df[df.sales==1].head()

498


In [25]:
import numpy as np
import pandas as pd
ar = np.zeros((1000,3))
columns = ['id','gender','age']
index = [np.arange(1000)]
df = pd.DataFrame(ar,index,columns=columns)
df

id  gender  age
0    0.0     0.0  0.0
1    0.0     0.0  0.0
2    0.0     0.0  0.0
3    0.0     0.0  0.0
4    0.0     0.0  0.0
..   ...     ...  ...
995  0.0     0.0  0.0
996  0.0     0.0  0.0
997  0.0     0.0  0.0
998  0.0     0.0  0.0
999  0.0     0.0  0.0

[1000 rows x 3 columns]